sudo: required
  
services:
  - docker

before_install:
  - docker build -t aeghobor/arcus -f Dockerfile.dev .

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "arcus"
  env: "Arcus-env"
  bucket_name: "elasticbeanstalk-eu-west-1-336209744632"
  bucket_path: "arcus"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
